### ISSUE TITLE
Geographic extraoplation does not follow clustering

### ISSUE THREAD

**Issue by casparbein** [bcm-uga/TESS3_encho_sen#23]
Hello Oliver,

I was running tess3R with unlinked sites only and then rerunning it with linked sites, the results came out very similar (as tess3R is model-free, I reckon linked SNPs are a biologically valid input). 

The Q-matrices/Barplots I get are nice and visually appealing, but when I plot the geographical interpolation, sometimes certain clusters do not appear. In my case, I ran the analysis for K=1-11, and for K=3, K=4, K=10 and K=11, the third cluster does not appear on the map. It is a well-defined cluster (3 individuals, >0.9 ancestry to this cluster) and other population structure analysis have corroborated it being distinct from the rest. It is plotted on the Q-matrix barplots in all cases and never splits into more clusters.  It also appears on the map for K=5 -9.

Any idea why it disappears? With the unlinked SNP dataset, the same cluster was plotted nicely from K=3 -8 (I did not run more Ks in that case), and I used the same code for both analyses:

```
## run the Tess MF algorithm
tess3_linked_K11.obj <- tess3(X = genotype, coord = as.matrix(coordinates), 
                               K = 1:11, 
                               method = "projected.ls", 
                               ploidy = 2, 
                               openMP.core.num = 4,
                               max.iteration = 1000,
                               rep = 20,
                               keep ="all"
)

## get Q-matrices
q.matrix_1 <- qmatrix(tess3_linked_K11.obj , K = 1)
q.matrix_2 <- qmatrix(tess3_linked_K11.obj , K = 2)
q.matrix_3 <- qmatrix(tess3_linked_K11.obj , K = 3)
q.matrix_4 <- qmatrix(tess3_linked_K11.obj , K = 4)
q.matrix_5 <- qmatrix(tess3_linked_K11.obj , K = 5)
q.matrix_6 <- qmatrix(tess3_linked_K11.obj , K = 6)
q.matrix_7 <- qmatrix(tess3_linked_K11.obj , K = 7)
q.matrix_8 <- qmatrix(tess3_linked_K11.obj , K = 8)
q.matrix_9 <- qmatrix(tess3_linked_K11.obj , K = 9)
q.matrix_10 <- qmatrix(tess3_linked_K11.obj , K = 10)
q.matrix_11 <- qmatrix(tess3_linked_K11.obj , K = 11)

## plot the interpolation, example for K=3
plot(q.matrix_3, coordinates, method="map.max", cex=1,
     raster.filename = "~/test_10.asc", 
     interpol=FieldsKrigModel(100),
     main=paste0("Ancestry coefficients"), resolution=c(300,300),
     xlab="longitude", ylab="Latitude")
```

I was thinking since this cluster is highly divergent and localized, it cannot be interpolated under certain circumstances. However, it surprises me that I get decent maps for K=5 - 9.

Any help is much appreciated.

Best regards,

Bernhard

**Comment by francoio** [comment]
hi, 

 In the spatial  interpolation, some clusters may be poorly interpolated, for example if their are small (check by changing method="map.max" to "map.all"). This not a problem with tess3 itself, but more a problem of the interpolation method.

I suggest to change  interpol=FieldsKrigModel(100) to  FieldsKrigModel(10) or to use FieldsTpsModel() with various theta values (see Tps). Displaying the ancestry matrix (barplot) could also help interpretations. 

best wishes
olivier

**Comment by casparbein** [comment]
Thanks a lot ! Changing the interpolation method from  FieldsKrigModel(100)  to  FieldsKrigModel(9.5) did the trick, at least for K=3 and 4 (which are more meaningful anyway).

We interpret the shading of the areas on the map after interpolation as the probability of a hypothetical individual sampled from this area to belong to a certain cluster, is that correct? If by changing the interpolation method parameter, I change the interpolation, is it still correct to interpret results that way? Because I tested values between 1 and 9.5 and interpolation results were sometimes rather different.

Thanks again, I really appreciate your help.
Cheers,
Bernhard

**Comment by francoio** [comment]
hello 
the geographic map is useful for the delimitation of genetic clusters and contact zones, but it does not replace the usual structure-like barplot, which is the most accurate way to display the ancestry coefficient matrix. So i suggest showing both the map and the barplot with the same colors for the clusters. 
best 
olivier 


De: "jdeboer-lizard-wizard" ***@***.***> 
À: "bcm-uga/TESS3_encho_sen" ***@***.***> 
Cc: "Olivier Francois" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Lundi 1 Novembre 2021 18:28:12 
Objet: Re: [bcm-uga/TESS3_encho_sen] Geographic extraoplation does not follow clustering (Issue #23) 





Thanks a lot ! Changing the interpolation method from FieldsKrigModel(100) to FieldsKrigModel(9.5) did the trick, at least for K=3 and 4 (which are more meaningful anyway). 

We interpret the shading of the areas on the map after interpolation as the probability of a hypothetical individual sampled from this area to belong to a certain cluster, is that correct? If by changing the interpolation method parameter, I change the interpolation, is it still correct to interpret results that way? Because I tested values between 1 and 9.5 and interpolation results were sometimes rather different. 

Thanks again, I really appreciate your help. 
Cheers, 
Bernhard

**Comment by casparbein** [comment]
Thanks a lot for you clarifications, I will include both.

Cheers, Bernhard
